### ISSUE TITLE
vue-light-bootstrap-dashboard-pro-v1.2.0-html

### ISSUE THREAD

**Issue by grabelle** [creativetimofficial/ct-light-bootstrap-dashboard-pro-laravel#1]
Hi,
I just bought this template : vue-light-bootstrap-dashboard-pro-v1.2.0
I would like to use it with laravel. How can I do to achieve that ?
I would really appreciate your help.

**Comment by teamupdivision** [comment]
Hello @grabelle, thanks for using our products!
This is not an issue with this current project.
To use vue-light-bootstrap with Laravel you should create a Laravel API.
All the best
