### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by booni3** [creativetimofficial/ct-light-bootstrap-dashboard-pro-laravel#2]
Hello,

I have purchased and downloaded this theme but cannot see any sass files in the download? The marketing page shows they should be there however...

https://www.creative-tim.com/product/light-bootstrap-dashboard-pro-laravel

Can you advise?

**Comment by teamupdivision** [comment]
Hello @booni3, thanks for using Creative Tim products!
Sorry for the inconvenience, please download the PRO archive again and you will find the Light Bootstrap files in the /public folder.

All the best!
